def includeme(config): 
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('auth', '/sign/{action}')
    config.add_route('register', '/register')
    config.add_route('admin', '/admin')
    config.add_route('students', '/student')
    config.add_route('student', '/student/{s}')
    config.add_route('student_course', '/student/{s}/{c}')
    config.add_route('professors', '/professor')
    config.add_route('professor', '/professor/{p}')
    config.add_route('professor_course', '/professor/{p}/{c}')
    config.add_route('add_work', '/professor/{p}/{c}/add')
    config.add_route('update_rating', '/professor/{p}/{c}/{w}')
